# Copyright 2024 Adevinta

version: "2.4"

services:
  lava-docs-build:
    build:
      context: .
    volumes:
      - .:/lava-docs
    environment:
      LAVA_VERSION: ${LAVA_VERSION:-latest}
    command: ["/lava-docs/docker/build.bash"]

  lava-docs-test:
    build:
      context: .
    volumes:
      - .:/lava-docs
    command: ["/lava-docs/docker/test.bash"]
